version = 1

[[annotations]]
path = [
  ".github/**",
  ".gitignore",
  ".mise.toml",
  ".swiftformat",
  "CHANGELOG.md",
  "Makefile",
  "NOTICE.md",
  "README.md",
  "Resources/**",
  "Tatami/Resources/**",
  "Tatami/Tatami.entitlements",
  "THIRD_PARTY_NOTICES.md",
  "demo/**",
  "docs/**",
  "web/**",
]
precedence = "closest"
SPDX-FileCopyrightText = "2026 PangMo5 and contributors"
SPDX-License-Identifier = "AGPL-3.0-only"

[[annotations]]
path = "Tuist/Package.resolved"
precedence = "override"
SPDX-FileCopyrightText = "NONE"
SPDX-License-Identifier = "CC0-1.0"
