#!/usr/bin/env python3
# SPDX-FileCopyrightText: 2026 PangMo5 and contributors
# SPDX-License-Identifier: AGPL-3.0-only
"""The website's dark palette is the single source of truth for film presentation."""
from pathlib import Path
import json
import re
ROOT=Path(__file__).resolve().parents[2]

def palette():
    blocks=re.findall(r':root\s*\{([^}]+)\}',(ROOT/'web/style.css').read_text())
    if len(blocks)<2: raise ValueError('website dark palette is missing')
    tokens={}
    for block in blocks[:2]:tokens.update(re.findall(r'--([\w-]+)\s*:\s*([^;]+);',block))
    def color(key):
        raw=tokens[key].strip().lstrip('#')
        if len(raw)==3:raw=''.join(x*2 for x in raw)
        if not re.fullmatch('[0-9a-fA-F]{6}',raw):raise ValueError(f'{key} is not a hex color')
        return raw.upper()
    return dict(background=color('bg-gray'),text=color('text'),secondary=color('text-secondary'),accent=color('accent'))

def bgr(rgb):return rgb[4:6]+rgb[2:4]+rgb[0:2]

def restyle(ass):
    colors=palette(); lines=[]
    for line in ass.splitlines():
        if line.startswith('Style: '):
            fields=line[7:].split(',')
            if fields[0] in ['Caption','Chapter','Keys']:
                color=colors['text'] if fields[0]=='Caption' else colors['accent']
                fields[3]=fields[4]='&H00'+bgr(color)
                line='Style: '+','.join(fields)
        if ',Caption,,' in line:
            line=re.sub(r'\\1c&H[0-9A-Fa-f]+&',lambda _: '\\1c&H'+bgr(colors['secondary'])+'&',line)
        lines.append(line)
    return '\n'.join(lines)+'\n'

def write_swift():
    p=palette()
    text='// Generated by scripts/video_theme.py from web/style.css.\n// SPDX-FileCopyrightText: 2026 PangMo5 and contributors\n// SPDX-License-Identifier: AGPL-3.0-only\nenum FilmTheme {\n'
    text+=f'  static let background = "{p["background"]}"\n'
    for key in ['text','secondary','accent']:text+=f'  static let {key} = "&H00{bgr(p[key])}"\n'
    text+='}\n'
    target=ROOT/'DemoLab/Sources/DemoCtlKit/FilmTheme.swift'
    if not target.exists() or target.read_text()!=text:target.write_text(text)

if __name__=='__main__':
    write_swift();print(json.dumps(palette(),indent=2))
