// Generated by scripts/video_theme.py from web/style.css.
// SPDX-FileCopyrightText: 2026 PangMo5 and contributors
// SPDX-License-Identifier: AGPL-3.0-only
enum FilmTheme {
  static let background = "1D1D1F"
  static let text = "&H00F7F5F5"
  static let secondary = "&H008B8686"
  static let accent = "&H0096CDE9"
}
