// SPDX-FileCopyrightText: 2026 PangMo5 and contributors
// SPDX-License-Identifier: AGPL-3.0-only

import Foundation

struct DependencyNotices {
  let workspace: Workspace

  func rendered() async throws -> String {
    let pins = try JSON.read(workspace.tools.at("Package.resolved"))["pins"].array
    try require(!pins.isEmpty, "Tools/Package.resolved has no packages")
    let checkouts = try workspace.tools.at(".build/checkouts").children()
    var output = """
      # Development Tool Dependency Notices

      This file covers the complete dependency graph pinned in `Tools/Package.resolved`, including build and test dependencies. It is separate from the dependencies of the distributed Tatami app, listed in [the app notices](../THIRD_PARTY_NOTICES.md).

      Generated by `swift run --package-path Tools tatami-tools build-tool-notices`. License and notice files are reproduced from the exact pinned Git revisions, including component notices inside those packages. Keep these original legal texts in their original language.

      <!-- REUSE-IgnoreStart -->

      """
    for pin in pins.sorted(by: { $0["identity"].str < $1["identity"].str }) {
      let identity = pin["identity"].str
      let revision = pin["state"]["revision"].str
      guard let checkout = checkouts.first(where: { $0.lastPathComponent.lowercased() == identity.lowercased() }) else {
        throw ToolError("Missing checkout for \(identity); run swift package --package-path Tools resolve")
      }
      let files = try await runProcess(["git", "-C", checkout.path, "ls-tree", "-r", "--name-only", revision], capture: true)
      let notices = lines(files).filter { path in
        fullMatch(#"(?i)(?:LICEN[CS]E|COPYING|NOTICE)(?:[._-].*)?"#, URL(fileURLWithPath: path).lastPathComponent)
      }.sorted()
      try require(!notices.isEmpty, "No license or notice files in \(identity) at \(revision)")
      var source = pin["location"].str
      if source.hasSuffix(".git") { source.removeLast(4) }
      output += "## \(identity) \(pin["state"]["version"].string ?? revision)\n\nSource: \(source)\n\nRevision: `\(revision)`\n\n"
      for path in notices {
        let contents = try await runProcess(["git", "-C", checkout.path, "show", "\(revision):\(path)"], capture: true)
        let fence = String(repeating: "~", count: max(4, matches("~+", contents).map { $0[0].count + 1 }.max() ?? 4))
        output += "### `\(path)`\n\n\(fence)text\n\(contents)\(contents.hasSuffix("\n") ? "" : "\n")\(fence)\n\n"
      }
    }
    return output + "<!-- REUSE-IgnoreEnd -->\n"
  }

  func build(check: Bool) async throws {
    let text = try await rendered()
    let file = workspace.tools.at("THIRD_PARTY_NOTICES.md")
    if check { try require(try file.text() == text, "Development tool notices have drifted from Package.resolved") }
    else { try file.write(text) }
    print("\(check ? "Verified" : "Generated") development tool dependency notices")
  }
}
